### ISSUE TITLE
Menghapus Kode yg Tidak Dibutuhkan

### ISSUE THREAD

**Issue by jefrydco** [dottomCode/submission-vuejs-app#1]
Hi Mas Tommy, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Tommy.

Mas juga sudah menggunakan kerangka kerja CSS Bootstrap untuk gaya aplikasi pencari teks video YouTube ini. Selain itu saya lihat Mas juga sudah menerapkan konsep penamaan CSS berformat BEM. Luar biasa Mas!

Namun saya ada 1 saran kecil Mas yakni menghapus kode yg tidak dibutuhkan. Pada berkas `index.html` baris ke 203-205 Mas menggunakan beberapa perpustakaan JavaScript eksternal:

https://github.com/dottomCode/submission-vuejs-app/blob/96dec71c0d83b0e7234b557f3aa3fca779ed3b5c/index.html#L203-L205

dan pada baris ke 207-212 berikut:

https://github.com/dottomCode/submission-vuejs-app/blob/96dec71c0d83b0e7234b557f3aa3fca779ed3b5c/index.html#L207-L212

Saya lihat pada aplikasi ini Mas tidak menggunakan fungsionalitas beberapa perpustakaan JavaScript eksternal tersebut, sehingga mungkin akan lebih baik jika Mas menghapusnya.

Semangat Mas! 😄 

---

## Update

Oiya Mas kelupaan, terima kasih banyak Mas sudah mendokumentasikan proses belajar Vue.js Fundamental di Medium. Saya benar benar mengapresiasi kerja keras yg Mas lakukan, luar biasa Mas! 🚀

**Comment by imotD** [comment]
Hi Mas Jefry, Terima kasih sebelumnya sudah mereview code saya dengan sangat teliti dan terima kasih atas saran yang disampaikan. Itu sangat berarti bagi saya.

**Comment by jefrydco** [comment]
Terima kasih kembali Mas, saya akan membiarkan isu ini terbuka ya Mas, nanti kalau misal Mas sudah ada waktu dan berkenan untuk memperbaikinya, Mas bisa menutup isu ini. Semangat selalu Mas! 😄

**Comment by imotD** [comment]
Sudah mas, Sudah saya update mas hehe :+1:

**Comment by jefrydco** [comment]
Wah terima kasih banyak Mas, kalau gitu saya tutup ya isu ini Mas. Semangat selalu Mas! 😄
